# Generated by Django 4.1.5 on 2023-01-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTrali',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=444)),
                ('product_catagory', models.CharField(max_length=444)),
                ('product_price', models.IntegerField()),
            ],
        ),
    ]
